summon minecraft:zoglin ~ ~ ~ star:rift_spawned "Rift Zoglin"
summon minecraft:zoglin ~ ~ ~ star:rift_spawned "Rift Zoglin"
summon minecraft:zoglin ~ ~ ~ star:rift_spawned "Rift Zoglin"
summon minecraft:zoglin ~ ~ ~ star:rift_spawned "Rift Zoglin"
summon minecraft:zoglin ~ ~ ~ star:rift_spawned "Rift Zoglin"

summon minecraft:spider ~ ~ ~ star:rift_spawned "Rift Spider"
summon minecraft:spider ~ ~ ~ star:rift_spawned "Rift Spider"
summon minecraft:spider ~ ~ ~ star:rift_spawned "Rift Spider"
summon minecraft:spider ~ ~ ~ star:rift_spawned "Rift Spider"
summon minecraft:spider ~ ~ ~ star:rift_spawned "Rift Spider"